// child-common-react-15/src/pages/Home/index.js
import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@alifd/next';
import { appHistory } from '@ice/stark-app';
import IceContainer from '@icedesign/container';
import PageTitle from '@/components/PageTitle';

export default function Home() {
  return (
    <IceContainer>
      <PageTitle title="首页" />
      <Link to="/about">子应用内跳转</Link>
      <br />
      <Button type="primary" onClick={() => {
        appHistory.push('/seller');
      }}>子应用间跳转</Button>
      <br />
    </IceContainer>
  );
}

// child-waiter-vue-2/src/pages/Home/Home.vue
<template>
  <div>
    <div>小二：首页</div>
    <router-link to="/detail">detail</router-link>
    <br />
    <router-link to="/list">list</router-link>
    <br />
    <el-button type="primary" @click="handleClick">子应用间跳转</el-button>
    <el-alert
      title="这是一个 Element 的组件"
      type="success"
    >
    </el-alert>
  </div>
</template>

<script>
import { appHistory } from '@ice/stark-app';

export default {
  methods: {
    handleClick: () => {
      appHistory.push('/');
    }
  }
}
</script>>
